### ISSUE TITLE
Add option to convert protocols of multiple demos without even launching of game

### ISSUE THREAD

**Issue by SmileyAG** [jpcy/coldemoplayer#4]
I know that CDP makes a converted demo with launching a game, named like `coldemoplayer.dem` and delete it after game was closed.

But I want actually skip steps with launching game and just convert multiple demos on older protocols to latest one.

**Comment by jpcy** [comment]
Conversion is destructive/one-way. You lose the ability to play the demo with the version it was recorded with. That's why converted demos are written to a temporary file - they shouldn't be distributed as a "converted demo". It's also possible the converted files could break with a future Valve update.

**Comment by SmileyAG** [comment]
> 
> 
> Conversion is destructive/one-way. You lose the ability to play the demo with the version it was recorded with. That's why converted demos are written to a temporary file - they shouldn't be distributed as a "converted demo".

I know, for that cases I'll do backup of original demos, so I don't think what issue should be closed, it's really useful option. 

I have about 6k+ tournament CS demos from older versions, and I don't want to run the game with CDP every time I want convert demo to latest protocol, I need to convert all demos which I selected at once via some option in application.

> It's also possible the converted files could break with a future Valve update.

Then someone will add support in CDP for converting demos to newest protocol, no? Or you can run this demos on an previous version of game at least.

I can't personally watch demos on older builds, cuz I have specific tools that are tied to steampipe binaries of the game and it will be difficult to add support for so oldest builds one. Like: https://github.com/YaLTeR/bxt-rs
